'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { api, Job, PlayerRecord, ServerAdminRecord, ServerInstance } from '../../../lib/api';
import { getStoredOrgId } from '../../../lib/auth';
import { useServerSelection } from '../../../lib/server-selection';
import { InventoryGrid, InventoryGridItem } from '../../../components/InventoryGrid';

type JobResult={data?:{admins?:ServerAdminRecord[]};errorMessage?:string;output?:string};
function inventorySections(snapshot:{bag?:InventoryGridItem[];belt?:InventoryGridItem[];equipment?:InventoryGridItem[];other?:InventoryGridItem[]}|null){
  if(!snapshot)return [] as Array<[string,InventoryGridItem[]]>;
  return [['Belt',snapshot.belt||[]],['Bag',snapshot.bag||[]],['Equipment',snapshot.equipment||[]],['Other',snapshot.other||[]]] as Array<[string,InventoryGridItem[]]>;
}
function duration(seconds:number){const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60);return h?`${h}h ${m}m`:`${m}m`;}

export default function PlayersPage(){
  const orgId=getStoredOrgId(); const [servers,setServers]=useState<ServerInstance[]>([]); const [serverId,setServerId]=useState('');
  const [players,setPlayers]=useState<PlayerRecord[]>([]); const [admins,setAdmins]=useState<ServerAdminRecord[]>([]); const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false); const [inventory,setInventory]=useState<{player:string;output:string;sections:Array<[string,InventoryGridItem[]]>}|null>(null);
  const [query,setQuery]=useState('');const [status,setStatus]=useState<'all'|'online'|'offline'|'admin'>('all');const [sort,setSort]=useState<'status'|'name'|'platform'|'ip'|'admin'|'entity'|'level'|'zombieKills'|'playerKills'|'deaths'|'session'|'lifetime'|'lastSeen'>('status');const [sortAsc,setSortAsc]=useState(false);const [lastRefresh,setLastRefresh]=useState<Date|null>(null);
  const selectServer=useServerSelection(servers,serverId,setServerId);
  useEffect(()=>{if(!orgId)return;api.get<ServerInstance[]>(`/api/orgs/${orgId}/server-instances`).then(rows=>setServers(rows.filter(row=>row.gameType==='minecraft'))).catch(e=>setError(e.message));},[orgId]);
  const waitForJob=useCallback(async(runId:string)=>{for(let i=0;i<120;i++){await new Promise(r=>setTimeout(r,1000));const run=await api.get<{status:string;result:JobResult|null}|null>(`/api/orgs/${orgId}/jobs/runs/${runId}`);if(run?.status==='failed')throw new Error(run.result?.errorMessage||'Agent job failed');if(run?.status==='success')return(run.result||{})as JobResult;}throw new Error('Agent job timed out');},[orgId]);
  const loadPlayers=useCallback(async()=>{if(!orgId||!serverId)return;try{setPlayers(await api.get<PlayerRecord[]>(`/api/orgs/${orgId}/players?serverInstanceId=${encodeURIComponent(serverId)}`));setLastRefresh(new Date());setError('');}catch(e){setError(e instanceof Error?e.message:'Failed to load players');}},[orgId,serverId]);
  const loadAdmins=useCallback(async()=>{if(!orgId||!serverId)return;try{const queued=await api.post<{jobRunId:string}>(`/api/orgs/${orgId}/jobs`,{serverInstanceId:serverId,type:'PLAYER_ADMIN_LIST',payload:{}});const result=await waitForJob(queued.jobRunId);setAdmins(result.data?.admins||[]);}catch(e){setError(e instanceof Error?e.message:'Failed to read serveradmin.xml');}},[orgId,serverId,waitForJob]);
  useEffect(()=>{void loadPlayers();const t=setInterval(()=>void loadPlayers(),5000);return()=>clearInterval(t);},[loadPlayers]);
  useEffect(()=>{if(serverId)void loadAdmins();},[serverId,loadAdmins]);
  async function moderationAction(player:PlayerRecord,type:'PLAYER_KICK'|'PLAYER_BAN'){
    if(!orgId)return;const identifier=player.steamId||(player.eosId?`EOS_${player.eosId}`:player.name);
    const reason=window.prompt(type==='PLAYER_KICK'?'Kick reason:':'Ban reason:',type==='PLAYER_KICK'?'Removed by administrator':'Banned by administrator');if(reason===null)return;
    const durationValue=type==='PLAYER_BAN'?window.prompt('Ban duration (examples: 1 days, 12 hours, 0 minutes for permanent):','1 days'):null;if(type==='PLAYER_BAN'&&durationValue===null)return;
    const platform=player.steamId?'Steam':player.eosId?'EOS':undefined;try{await api.post(`/api/orgs/${orgId}/jobs`,{serverInstanceId:serverId,type,payload:{identifier,platform,reason,...(durationValue?{duration:durationValue}:{})}});setMessage(`${type==='PLAYER_KICK'?'Kick':'Ban'} queued for ${player.name}.`);setError('');}catch(e){setError(e instanceof Error?e.message:'Command failed');}
  }
  async function kickAll(){
    if(!orgId||!serverId||busy)return;const reason=window.prompt('Reason shown to every kicked player:','Server maintenance');if(reason===null)return;if(!confirm(`Kick all ${players.filter(player=>player.online).length} online player(s)?`))return;
    setBusy(true);setError('');setMessage('');try{const queued=await api.post<{jobRunId:string}>(`/api/orgs/${orgId}/jobs`,{serverInstanceId:serverId,type:'PLAYER_KICK_ALL',payload:{reason}});await waitForJob(queued.jobRunId);await loadPlayers();setMessage('Kick all completed and verified: 0 players online.');}catch(e){setError(e instanceof Error?e.message:'Kick all failed');}finally{setBusy(false);}
  }
  function adminFor(player:PlayerRecord){const ids=[player.steamId,player.eosId,player.eosId?`EOS_${player.eosId}`:null].filter(Boolean).map(v=>String(v).toLowerCase());return admins.find(a=>ids.includes(a.userId.toLowerCase())||(!ids.length&&a.name?.toLowerCase()===player.name.toLowerCase()));}
  async function adminAction(player:PlayerRecord,promote:boolean){
    if(!orgId||busy)return;const identifier=player.steamId||(player.eosId?`EOS_${player.eosId}`:'');if(!identifier){setError('Steam or EOS ID required for admin changes.');return;}
    const verb=promote?'promote':'demote';if(!confirm(`${promote?'Promote':'Demote'} ${player.name} ${promote?'to':'from'} Minecraft operator?`))return;
    const platform=player.steamId?'Steam':'EOS';setBusy(true);setError('');setMessage('');try{const queued=await api.post<{jobRunId:string}>(`/api/orgs/${orgId}/jobs`,{serverInstanceId:serverId,type:promote?'PLAYER_ADMIN_PROMOTE':'PLAYER_ADMIN_DEMOTE',payload:{platform,identifier}});await waitForJob(queued.jobRunId);await loadAdmins();setMessage(`${player.name} ${verb}d successfully. serveradmin.xml refreshed.`);}catch(e){setError(e instanceof Error?e.message:`Failed to ${verb} player`);}finally{setBusy(false);}
  }
  async function setDeaths(player:PlayerRecord){
    if(!orgId||busy)return;
    if(!player.online){setError('The player must be online for ServerTools to change their death count.');return;}
    const raw=window.prompt(`Set death count for ${player.name}:`,String(player.deaths));
    if(raw===null)return;
    const deaths=Number(raw.trim());
    if(!Number.isInteger(deaths)||deaths<0||deaths>100000){setError('Deaths must be a whole number from 0 to 100000.');return;}
    const identifier=player.steamId||(player.eosId?`EOS_${player.eosId}`:player.entityId!=null?String(player.entityId):player.name);
    const platform=player.steamId?'Steam':player.eosId?'EOS':undefined;
    setBusy(true);setError('');setMessage('');
    try{
      const queued=await api.post<{jobRunId:string}>(`/api/orgs/${orgId}/jobs`,{serverInstanceId:serverId,type:'PLAYER_SET_DEATHS',payload:{identifier,platform,deaths,playerId:player.id,steamId:player.steamId,eosId:player.eosId,entityId:player.entityId,name:player.name}});
      await waitForJob(queued.jobRunId);
      await loadPlayers();
      setMessage(`Set ${player.name}'s deaths to ${deaths}.`);
    }catch(e){setError(e instanceof Error?e.message:'Could not set deaths');}
    finally{setBusy(false);}
  }
  async function showInventory(player:PlayerRecord){
    if(!orgId||(!player.steamId&&!player.eosId)||busy)return;
    setBusy(true);setError('');setMessage('');try{const result=await api.get<{player:string;snapshot:{bag:InventoryGridItem[];belt:InventoryGridItem[];equipment:InventoryGridItem[];other?:InventoryGridItem[]}}>(`/api/orgs/${orgId}/players/${player.id}/inventory`);setInventory({player:result.player||player.name,output:JSON.stringify(result.snapshot,null,2),sections:inventorySections(result.snapshot)});}catch(e){setError(e instanceof Error?e.message:'Failed to read player inventory');}finally{setBusy(false);}
  }
  const visible=useMemo(()=>players.filter(player=>{const admin=adminFor(player);if(status==='online'&&!player.online)return false;if(status==='offline'&&player.online)return false;if(status==='admin'&&!admin)return false;const text=`${player.name} ${player.steamId||''} ${player.eosId||''} ${player.ipAddress||''}`.toLowerCase();return text.includes(query.trim().toLowerCase());}).sort((a,b)=>{const aa=adminFor(a),bb=adminFor(b);let result=0;switch(sort){case 'status':result=Number(b.online)-Number(a.online);break;case 'name':result=a.name.localeCompare(b.name);break;case 'platform':result=(a.steamId||a.eosId||'').localeCompare(b.steamId||b.eosId||'');break;case 'ip':result=(a.ipAddress||'').localeCompare(b.ipAddress||'');break;case 'admin':result=Number(Boolean(bb))-Number(Boolean(aa))||(bb?.permissionLevel||0)-(aa?.permissionLevel||0);break;case 'entity':result=(a.entityId??-1)-(b.entityId??-1);break;case 'level':result=a.level-b.level;break;case 'zombieKills':result=a.zombieKills-b.zombieKills;break;case 'playerKills':result=a.playerKills-b.playerKills;break;case 'deaths':result=a.deaths-b.deaths;break;case 'session':result=a.sessionSeconds-b.sessionSeconds;break;case 'lifetime':result=a.lifetimeSeconds-b.lifetimeSeconds;break;case 'lastSeen':result=new Date(a.lastSeenAt).getTime()-new Date(b.lastSeenAt).getTime();break;}return (sortAsc?result:-result)||a.name.localeCompare(b.name);}),[players,admins,query,status,sort,sortAsc]);
  const onlineCount=players.filter(p=>p.online).length,adminCount=players.filter(p=>adminFor(p)).length;
  function actions(p:PlayerRecord,admin:ServerAdminRecord|undefined){return <div className="player-actions"><button disabled={(!p.steamId&&!p.eosId)||busy} onClick={()=>void showInventory(p)} style={button('#0369a1')}>Inventory</button><button disabled={!p.online||busy} onClick={()=>void setDeaths(p)} style={button('#6d28d9')}>Deaths</button><button disabled={!p.online||busy} onClick={()=>moderationAction(p,'PLAYER_KICK')} style={button('#b45309')}>Kick</button><button disabled={busy} onClick={()=>moderationAction(p,'PLAYER_BAN')} style={button('#991b1b')}>Ban</button>{admin?<button disabled={busy} onClick={()=>adminAction(p,false)} style={button('#7c2d12')}>Demote</button>:<button disabled={busy||(!p.steamId&&!p.eosId)} onClick={()=>adminAction(p,true)} style={button('#15803d')}>Promote</button>}</div>}
  return <div className="players-page"><div className="players-header"><div><h1 style={{margin:0,color:'#f1f5f9',fontSize:'1.5rem'}}>Players</h1><p style={{color:'#64748b',margin:'.25rem 0 0'}}>Live presence from <code>lp</code> · refreshes every 5 seconds{lastRefresh?` · updated ${lastRefresh.toLocaleTimeString()}`:''}</p></div><div className="players-header-actions"><button disabled={busy||!serverId} onClick={()=>void kickAll()} style={button('#991b1b')}>Kick all online</button><button disabled={busy||!serverId} onClick={()=>{void loadPlayers();void loadAdmins();}} style={button('#334155')}>Refresh now</button><select aria-label="Server" value={serverId} onChange={e=>selectServer(e.target.value)} style={{background:'#111118',color:'#e2e8f0',border:'1px solid #252532',borderRadius:6,padding:'.5rem',maxWidth:'100%'}}>{servers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div></div>
  {error&&<div style={{color:'#f87171',marginBottom:10}}>{error}</div>}{message&&<div style={{color:'#4ade80',marginBottom:10}}>{message}</div>}
  <div className="player-summary-grid"><Summary label="Online now" value={onlineCount} color="#4ade80"/><Summary label="Known players" value={players.length} color="#38bdf8"/><Summary label="Administrators" value={adminCount} color="#fbbf24"/><Summary label="Showing" value={visible.length} color="#a78bfa"/></div>
  <div className="player-toolbar"><input aria-label="Search players" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, Steam ID, EOS ID, or IP…"/><select aria-label="Player status" value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">All players</option><option value="online">Online</option><option value="offline">Offline</option><option value="admin">Administrators</option></select><select aria-label="Sort players" value={sort} onChange={e=>{setSort(e.target.value as typeof sort);setSortAsc(e.target.value==='status'?false:true);}}><option value="status">Online first</option><option value="name">Name</option><option value="platform">Steam / EOS ID</option><option value="ip">IP address</option><option value="admin">Admin status</option><option value="entity">Entity ID</option><option value="level">Level</option><option value="zombieKills">Zombie kills</option><option value="playerKills">Player kills</option><option value="deaths">Deaths</option><option value="session">Session playtime</option><option value="lifetime">Lifetime playtime</option><option value="lastSeen">Last seen</option></select><button type="button" onClick={()=>setSortAsc(value=>!value)} style={button('#334155')} title="Toggle sort direction">{sortAsc?'Asc ▲':'Desc ▼'}</button>{(query||status!=='all')&&<button onClick={()=>{setQuery('');setStatus('all');}} style={button('#334155')}>Clear</button>}</div>
  {inventory&&<div className="player-inventory-panel"><div className="player-inventory-head"><strong style={{color:'#e2e8f0'}}>{inventory.player}&apos;s inventory</strong><button onClick={()=>setInventory(null)} style={button('#334155')}>Close</button></div>{inventory.sections.some(([,items])=>items.length>0)?<InventoryGrid sections={inventory.sections}/>:null}<details style={{marginTop:12}}><summary style={{color:'#94a3b8',cursor:'pointer'}}>Raw Allocs inventory JSON</summary><pre style={{color:'#cbd5e1',whiteSpace:'pre-wrap',overflowWrap:'anywhere',maxHeight:240,overflowY:'auto',margin:'8px 0 0',fontSize:'.78rem'}}>{inventory.output}</pre></details></div>}
  <div className="player-card-list">{visible.length===0?<div className="player-card player-card-empty">{players.length?'No players match current filters.':'No players discovered yet. Records appear after a roster poll.'}</div>:visible.map(p=>{const admin=adminFor(p);return <article key={p.id} className="player-card"><div className="player-card-main"><div className="player-card-head"><div><strong>{p.name}</strong><div className="player-status" style={{color:p.online?'#4ade80':'#64748b'}}>{p.online?'● Online':'○ Offline'}{admin?` · Admin L${admin.permissionLevel}`:''}{p.entityId!=null?` · Entity ${p.entityId}`:''}</div></div><span className="player-level">Lv {p.level}</span></div><div className="player-meta"><code className="player-id">{p.steamId||p.eosId||'No platform ID'}</code><span className="player-ip">IP {p.ipAddress||'—'}</span><span className="player-seen">Seen {new Date(p.lastSeenAt).toLocaleString()}</span></div></div><div className="player-stat-grid"><span><small>Session</small>{duration(p.sessionSeconds)}</span><span><small>Lifetime</small>{duration(p.lifetimeSeconds)}</span><span><small>Zombies</small>{p.zombieKills}</span><span><small>Players</small>{p.playerKills}</span><span><small>Deaths</small>{p.deaths}</span><span><small>Platform</small>{p.steamId?'Steam':p.eosId?'EOS':'Name'}</span></div>{actions(p,admin)}</article>})}</div></div>;
}
function Summary({label,value,color}:{label:string;value:number;color:string}){return <div className="player-summary"><small>{label}</small><strong style={{color}}>{value}</strong></div>}
function button(background:string){return{background,color:'white',border:0,borderRadius:5,padding:'.4rem .6rem',cursor:'pointer' as const};}
