'use client';
import {useEffect,useState} from 'react';
import {api,ServerInstance} from '../../../lib/api';
import {getStoredOrgId} from '../../../lib/auth';
import {useServerSelection} from '../../../lib/server-selection';

type Settings={highPingEnabled:boolean;highPingThresholdMs:number;highPingSamples:number;highPingReason:string;countryBanEnabled:boolean;blockedCountryCodes:string[];countryAction:'kick'|'ban';countryBanDuration:string;countryReason:string};
const defaults:Settings={highPingEnabled:false,highPingThresholdMs:250,highPingSamples:3,highPingReason:'Connection latency remained too high',countryBanEnabled:false,blockedCountryCodes:[],countryAction:'kick',countryBanDuration:'365 days',countryReason:'Connections from your country are not allowed'};
export default function ToolsPage(){
 const orgId=getStoredOrgId();const[servers,setServers]=useState<ServerInstance[]>([]);const[serverId,setServerId]=useState('');const[settings,setSettings]=useState(defaults);const[countries,setCountries]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');
 const selectServer=useServerSelection(servers,serverId,setServerId);
 useEffect(()=>{if(!orgId)return;api.get<ServerInstance[]>(`/api/orgs/${orgId}/server-instances`).then(rows=>setServers(rows.filter(r=>r.gameType==='minecraft'))).catch(e=>setError(e.message));},[orgId]);
 useEffect(()=>{if(!orgId||!serverId)return;setBusy(true);api.get<Settings>(`/api/orgs/${orgId}/server-tools/${serverId}`).then(value=>{setSettings(value);setCountries(value.blockedCountryCodes.join(', '));setError('');}).catch(e=>setError(e.message)).finally(()=>setBusy(false));},[orgId,serverId]);
 async function save(){if(!orgId||!serverId)return;setBusy(true);setMessage('');setError('');try{const blockedCountryCodes=countries.split(/[\s,;]+/).map(x=>x.trim().toUpperCase()).filter(Boolean);const saved=await api.patch<Settings>(`/api/orgs/${orgId}/server-tools/${serverId}`,{...settings,blockedCountryCodes});setSettings(saved);setCountries(saved.blockedCountryCodes.join(', '));setMessage('Connection protection saved. Changes apply during next player check.');}catch(e){setError(e instanceof Error?e.message:'Save failed');}finally{setBusy(false);}}
 return <div><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap',marginBottom:'1rem'}}><div><h1 style={{margin:0,color:'#f1f5f9',fontSize:'1.5rem'}}>Server Tools</h1><p style={{color:'#64748b',margin:'.25rem 0 0'}}>Automatic connection protection, checked every minute.</p></div><select value={serverId} onChange={e=>selectServer(e.target.value)} style={input}>{servers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>
 {error&&<p style={{color:'#f87171'}}>{error}</p>}{message&&<p style={{color:'#4ade80'}}>{message}</p>}
 <div style={grid}><section style={card}><h2 style={heading}>High ping kicker</h2><p style={help}>Kicks player only after several consecutive bad readings. One spike will not trigger it.</p><Toggle label="Enable high ping kicker" checked={settings.highPingEnabled} onChange={v=>setSettings({...settings,highPingEnabled:v})}/><Field label="Maximum ping (ms)"><input type="number" min={50} max={5000} value={settings.highPingThresholdMs} onChange={e=>setSettings({...settings,highPingThresholdMs:Number(e.target.value)})} style={input}/></Field><Field label="Consecutive bad checks"><input type="number" min={2} max={20} value={settings.highPingSamples} onChange={e=>setSettings({...settings,highPingSamples:Number(e.target.value)})} style={input}/></Field><Field label="Kick reason"><input value={settings.highPingReason} onChange={e=>setSettings({...settings,highPingReason:e.target.value})} style={input}/></Field></section>
 <section style={card}><h2 style={heading}>Country ban</h2><p style={help}>Looks up public player IP country, then kicks or bans matching ISO country codes.</p><Toggle label="Enable country enforcement" checked={settings.countryBanEnabled} onChange={v=>setSettings({...settings,countryBanEnabled:v})}/><Field label="Blocked country codes"><input value={countries} onChange={e=>setCountries(e.target.value)} placeholder="RU, CN, KP" style={input}/><small style={help}>Two-letter ISO codes, comma-separated.</small></Field><Field label="Action"><select value={settings.countryAction} onChange={e=>setSettings({...settings,countryAction:e.target.value as 'kick'|'ban'})} style={input}><option value="kick">Kick</option><option value="ban">Ban</option></select></Field>{settings.countryAction==='ban'&&<Field label="Ban duration"><input value={settings.countryBanDuration} onChange={e=>setSettings({...settings,countryBanDuration:e.target.value})} placeholder="365 days" style={input}/></Field>}<Field label="Reason"><input value={settings.countryReason} onChange={e=>setSettings({...settings,countryReason:e.target.value})} style={input}/></Field><div style={{...help,color:'#f59e0b'}}>Private or relay-masked IPs are skipped. Country detection requires server to see each player&apos;s real public IP.</div></section></div>
 <button disabled={busy||!serverId} onClick={()=>void save()} style={button}>{busy?'Working…':'Save tools'}</button></div>;
}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}){return <label style={{display:'flex',gap:9,alignItems:'center',color:'#e2e8f0',margin:'1rem 0'}}><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/>{label}</label>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{display:'grid',gap:6,color:'#94a3b8',fontSize:'.8rem',marginBottom:12}}>{label}{children}</label>}
const grid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:'1rem',marginBottom:'1rem'};const card:React.CSSProperties={background:'#111118',border:'1px solid #252532',borderRadius:9,padding:'1.1rem'};const heading:React.CSSProperties={color:'#f1f5f9',fontSize:'1rem',margin:0};const help:React.CSSProperties={color:'#64748b',fontSize:'.78rem',lineHeight:1.5};const input:React.CSSProperties={background:'#0d0d14',color:'#e2e8f0',border:'1px solid #303044',borderRadius:6,padding:'.55rem',width:'100%',boxSizing:'border-box'};const button:React.CSSProperties={background:'#4f46e5',color:'white',border:0,borderRadius:6,padding:'.65rem 1rem',cursor:'pointer'};
