'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {api,ChatMessage,ServerInstance} from '../../../lib/api';
import {getStoredOrgId} from '../../../lib/auth';
import {useServerSelection} from '../../../lib/server-selection';

export default function ChatPage(){
 const orgId=getStoredOrgId();const [servers,setServers]=useState<ServerInstance[]>([]);const [serverId,setServerId]=useState('');const [messages,setMessages]=useState<ChatMessage[]>([]);const [enabled,setEnabled]=useState(false);const [webhookUrl,setWebhookUrl]=useState('');const [saving,setSaving]=useState(false);const [reply,setReply]=useState('');const [sending,setSending]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [autoScroll,setAutoScroll]=useState(true);const [moderation,setModeration]=useState<Moderation>({enabled:false,badWordRules:[],badWords:[],badWordAction:'warn',floodEnabled:true,floodMessages:5,floodWindowSeconds:10,floodAction:'kick',mutedPlayers:[]});const [newRuleWord,setNewRuleWord]=useState('');const [newRuleAction,setNewRuleAction]=useState<ModerationAction>('warn');const bottom=useRef<HTMLDivElement>(null);
 const selectServer=useServerSelection(servers,serverId,setServerId);
 useEffect(()=>{if(!orgId)return;api.get<ServerInstance[]>(`/api/orgs/${orgId}/server-instances`).then(rows=>setServers(rows.filter(row=>row.gameType==='minecraft'))).catch(e=>setError(e.message));},[orgId]);
 const load=useCallback(async()=>{if(!orgId||!serverId)return;try{setMessages(await api.get<ChatMessage[]>(`/api/orgs/${orgId}/chat?serverInstanceId=${encodeURIComponent(serverId)}&limit=300`));setError('');}catch(e){setError(e instanceof Error?e.message:'Failed to load chat');}},[orgId,serverId]);
 useEffect(()=>{if(!orgId||!serverId)return;api.get<{enabled:boolean;webhookUrl:string}>(`/api/orgs/${orgId}/chat/settings?serverInstanceId=${encodeURIComponent(serverId)}`).then(s=>{setEnabled(s.enabled);setWebhookUrl(s.webhookUrl);}).catch(e=>setError(e.message));api.get<Moderation>(`/api/orgs/${orgId}/chat/moderation?serverInstanceId=${encodeURIComponent(serverId)}`).then(s=>setModeration({...s,badWordRules:s.badWordRules??(s.badWords??[]).map(word=>({word,action:s.badWordAction??'warn'}))})).catch(e=>setError(e.message));void load();const timer=setInterval(()=>void load(),3000);return()=>clearInterval(timer);},[orgId,serverId,load]);
 useEffect(()=>{try{setAutoScroll(localStorage.getItem('mm_chat_autoscroll_v1')!=='false');}catch{/* Browser storage may be unavailable. */}},[]);
 useEffect(()=>{if(autoScroll)bottom.current?.scrollIntoView({behavior:'auto'});},[messages,autoScroll]);
 function toggleAutoScroll(){setAutoScroll(current=>{const next=!current;try{localStorage.setItem('mm_chat_autoscroll_v1',String(next));}catch{/* Keep the in-memory setting. */}if(next)requestAnimationFrame(()=>bottom.current?.scrollIntoView({behavior:'auto'}));return next;});}
 async function save(){if(!orgId||!serverId)return;setSaving(true);setNotice('');try{await api.post(`/api/orgs/${orgId}/chat/settings`,{serverInstanceId:serverId,enabled,webhookUrl});setNotice('Chat relay settings saved.');setError('');}catch(e){setError(e instanceof Error?e.message:'Failed to save relay');}finally{setSaving(false);}}
 async function sendReply(e:React.FormEvent){e.preventDefault();const text=reply.trim();if(!orgId||!serverId||!text||sending)return;setSending(true);setNotice('');setError('');try{const escaped=text.replace(/\\/g,'\\\\').replace(/"/g,'\\"');const queued=await withTimeout(api.post<{jobRunId:string}>(`/api/orgs/${orgId}/jobs`,{serverInstanceId:serverId,type:'RCON',payload:{command:`say "${escaped}"`}}),10000,'Server message request timed out before it was queued');let done:ChatJobRun|null=null;for(let i=0;i<120;i++){done=await withTimeout(api.get<ChatJobRun|null>(`/api/orgs/${orgId}/jobs/runs/${queued.jobRunId}`),5000,'Unable to read message job status');if(done?.status==='success'||done?.status==='failed')break;await new Promise(resolve=>setTimeout(resolve,250));}if(done?.status!=='success')throw new Error(done?.result?.errorMessage||'Server message did not complete within 30 seconds');setReply('');setNotice('Server message sent.');}catch(e){setError(e instanceof Error?e.message:'Failed to send server message');}finally{setSending(false);}}
 async function saveModeration(next=moderation,message='Chat moderation settings saved.'){if(!orgId||!serverId)return false;setSaving(true);setNotice('');try{const saved=await api.post<Moderation>(`/api/orgs/${orgId}/chat/moderation`,{...next,serverInstanceId:serverId});setModeration(saved);setNotice(message);setError('');return true;}catch(e){setError(e instanceof Error?e.message:'Failed to save moderation');return false;}finally{setSaving(false);}}
 async function setModerationEnabled(enabled:boolean){const next={...moderation,enabled};setModeration(next);await saveModeration(next,enabled?'Chat moderation enabled. Warnings and enforcement are active.':'Chat moderation disabled. Rules are retained but will not run.');}
 async function addBadWordRule(){const word=newRuleWord.trim().toLowerCase();if(!word){setError('Enter a word or phrase first.');return;}if(moderation.badWordRules.some(rule=>rule.word.toLowerCase()===word)){setError('That word or phrase already has a rule.');return;}const rules=[...moderation.badWordRules,{word,action:newRuleAction}];if(await saveModeration({...moderation,badWordRules:rules},`Added moderation rule for “${word}”.`))setNewRuleWord('');}
 async function deleteBadWordRule(index:number){const removed=moderation.badWordRules[index];const rules=moderation.badWordRules.filter((_,ruleIndex)=>ruleIndex!==index);await saveModeration({...moderation,badWordRules:rules},`Deleted moderation rule for “${removed.word}”.`);}
 async function toggleMute(playerId:string,playerName:string,muted:boolean){if(!orgId||!serverId)return;try{const saved=await api.post<Moderation>(`/api/orgs/${orgId}/chat/mute`,{serverInstanceId:serverId,playerId,playerName,muted});setModeration(saved);setNotice(muted?`${playerName} muted.`:`${playerName} unmuted.`);}catch(e){setError(e instanceof Error?e.message:'Mute action failed');}}
 return <div><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'start',flexWrap:'wrap',marginBottom:'1rem'}}><div><h1 style={{margin:0,color:'#f1f5f9',fontSize:'1.5rem'}}>Player Chat</h1><p style={{color:'#64748b',margin:'.25rem 0 0'}}>Player-sent messages parsed from Minecraft logs. Server and console announcements are excluded.</p></div><select value={serverId} onChange={e=>selectServer(e.target.value)} style={input}>{servers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div>
 {error&&<div style={{color:'#f87171',marginBottom:10}}>{error}</div>}{notice&&<div style={{color:'#4ade80',marginBottom:10}}>{notice}</div>}
 <div style={{background:'#111118',border:'1px solid #252532',borderRadius:9,padding:'1rem',marginBottom:'1rem'}}><strong style={{color:'#e2e8f0'}}>Discord chat relay</strong><div style={{display:'flex',gap:8,alignItems:'center',marginTop:'.7rem',flexWrap:'wrap'}}><label style={{color:'#94a3b8',display:'flex',gap:6,alignItems:'center'}}><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/> Enabled</label><input type="url" value={webhookUrl} onChange={e=>setWebhookUrl(e.target.value)} placeholder="https://discord.com/api/webhooks/…" style={{...input,flex:1,minWidth:240}}/><button disabled={saving} onClick={save} style={button}>{saving?'Saving…':'Save relay'}</button></div><small style={{color:'#64748b'}}>Only new player messages are relayed. Discord mentions are neutralized to prevent unwanted pings.</small></div>
 <section style={card}>
  <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><strong style={{color:'#e2e8f0'}}>Chat moderation</strong><div style={{color:'#64748b',fontSize:'.8rem',marginTop:3}}>Control flooding and assign a separate response to every blocked word or phrase.</div></div><button disabled={saving} onClick={()=>void saveModeration()} style={button}>{saving?'Saving…':'Save moderation settings'}</button></div>
  <div style={{display:'flex',gap:12,flexWrap:'wrap',marginTop:14,alignItems:'center'}}><label style={label}><input type="checkbox" checked={moderation.enabled} disabled={saving} onChange={e=>void setModerationEnabled(e.target.checked)}/> Moderation enabled</label><strong role="status" style={{color:moderation.enabled?'#4ade80':'#f87171',fontSize:'.8rem'}}>{moderation.enabled?'ACTIVE':'OFF — word rules will not run'}</strong><label style={label}><input type="checkbox" checked={moderation.floodEnabled} onChange={e=>setModeration({...moderation,floodEnabled:e.target.checked})}/> Flood control</label><label style={label}>Messages <input type="number" min={2} max={30} value={moderation.floodMessages} onChange={e=>setModeration({...moderation,floodMessages:Number(e.target.value)})} style={{...input,width:70}}/></label><label style={label}>Within seconds <input type="number" min={2} max={300} value={moderation.floodWindowSeconds} onChange={e=>setModeration({...moderation,floodWindowSeconds:Number(e.target.value)})} style={{...input,width:70}}/></label><select aria-label="Flood moderation action" value={moderation.floodAction} onChange={e=>setModeration({...moderation,floodAction:e.target.value as ModerationAction})} style={input}><option value="log">Log flood only</option><option value="warn">Warn player</option><option value="kick">Kick player</option></select></div>
  <div style={{borderTop:'1px solid #252532',marginTop:16,paddingTop:16}}>
   <div style={{display:'flex',justifyContent:'space-between',alignItems:'baseline',gap:10,flexWrap:'wrap'}}><strong style={{color:'#cbd5e1'}}>Word directory</strong><span style={{color:'#64748b',fontSize:'.78rem'}}>{moderation.badWordRules.length} of 200 rules</span></div>
   <form onSubmit={e=>{e.preventDefault();void addBadWordRule();}} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:8,marginTop:10}}><input value={newRuleWord} maxLength={80} onChange={e=>setNewRuleWord(e.target.value)} placeholder="Add a word or phrase" aria-label="New blocked word or phrase" style={input}/><select value={newRuleAction} onChange={e=>setNewRuleAction(e.target.value as ModerationAction)} aria-label="New rule action" style={input}><ActionOptions/></select><button disabled={saving||moderation.badWordRules.length>=200||!newRuleWord.trim()} style={button}>Add rule</button></form>
   <div style={{marginTop:10,border:'1px solid #252532',borderRadius:7,overflow:'hidden'}}>
    {moderation.badWordRules.length===0?<div style={{padding:'1rem',color:'#64748b',textAlign:'center'}}>No word rules yet. Add one above to begin filtering chat.</div>:moderation.badWordRules.map((rule,index)=><div key={index} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:8,padding:8,alignItems:'center',borderBottom:index===moderation.badWordRules.length-1?0:'1px solid #20202b'}}><input value={rule.word} maxLength={80} aria-label={`Blocked word ${index+1}`} onChange={e=>setModeration({...moderation,badWordRules:moderation.badWordRules.map((item,itemIndex)=>itemIndex===index?{...item,word:e.target.value}:item)})} style={input}/><select value={rule.action} aria-label={`Action for ${rule.word}`} onChange={e=>setModeration({...moderation,badWordRules:moderation.badWordRules.map((item,itemIndex)=>itemIndex===index?{...item,action:e.target.value as ModerationAction}:item)})} style={input}><ActionOptions/></select><div style={{display:'flex',gap:6}}><button disabled={saving||!rule.word.trim()} onClick={()=>void saveModeration()} style={{...button,background:'#334155',padding:'.5rem .7rem'}}>Save</button><button disabled={saving} onClick={()=>void deleteBadWordRule(index)} aria-label={`Delete ${rule.word}`} style={{...button,background:'#991b1b',padding:'.5rem .7rem'}}>Delete</button></div></div>)}
   </div>
  </div>
  <small style={{color:'#64748b',display:'block',marginTop:10}}>Log records the match without messaging the player. Warn sends a server warning. Kick removes the player. Matched and muted messages stay in the audit transcript but are not sent to Discord.</small>
 </section>
 <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,padding:'.6rem .75rem',background:'#111118',border:'1px solid #252532',borderRadius:'9px 9px 0 0'}}><strong style={{color:'#e2e8f0'}}>Chat transcript</strong><button type="button" aria-pressed={autoScroll} onClick={toggleAutoScroll} style={{...button,background:autoScroll?'#166534':'#334155',padding:'.4rem .7rem'}}>{autoScroll?'Autoscroll: On':'Autoscroll: Off'}</button></div><div style={{height:'calc(100vh - 600px)',minHeight:320,overflowY:'auto',background:'#08080c',border:'1px solid #1e1e2a',borderTop:0,padding:'1rem'}}>{messages.length===0?<div style={{color:'#64748b'}}>No player chat recorded yet.</div>:messages.map(row=>{const muted=moderation.mutedPlayers.some(p=>p.playerId===row.payload.playerId);return <div key={row.id} style={{display:'grid',gridTemplateColumns:'150px minmax(130px,210px) 1fr',gap:10,padding:'.45rem 0',borderBottom:'1px solid #15151d',alignItems:'start'}}><time style={{color:'#475569',fontSize:'.75rem'}}>{new Date(row.createdAt).toLocaleString()}</time><div><strong style={{color:'#818cf8',overflowWrap:'anywhere'}}>{row.payload.playerName}</strong>{row.payload.playerId!=='-non-player-'&&<button onClick={()=>toggleMute(row.payload.playerId,row.payload.playerName,!muted)} style={{...button,background:muted?'#166534':'#7f1d1d',padding:'.2rem .45rem',marginLeft:6,fontSize:'.7rem'}}>{muted?'Unmute':'Mute'}</button>}</div><div style={{color:'#cbd5e1',whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{row.payload.message}<small style={{color:'#475569',marginLeft:8}}>{row.payload.channel}</small></div></div>})}<div ref={bottom}/></div><form onSubmit={sendReply} style={{display:'flex',gap:8,background:'#111118',border:'1px solid #252532',borderTop:0,borderRadius:'0 0 9px 9px',padding:'.75rem'}}><span style={{color:'#64748b',alignSelf:'center',fontFamily:'monospace'}}>say</span><input value={reply} onChange={e=>setReply(e.target.value.replace(/[\r\n]/g,''))} maxLength={400} disabled={!serverId||sending} placeholder="Message players as Server…" aria-label="Server chat message" style={{...input,flex:1,minWidth:0}}/><button disabled={!serverId||!reply.trim()||sending} style={button}>{sending?'Sending…':'Send as Server'}</button></form></div>;
}
type ModerationAction='log'|'warn'|'kick';
type Moderation={enabled:boolean;badWordRules:Array<{word:string;action:ModerationAction}>;badWords:string[];badWordAction:ModerationAction;floodEnabled:boolean;floodMessages:number;floodWindowSeconds:number;floodAction:ModerationAction;mutedPlayers:Array<{playerId:string;playerName:string;createdAt:string}>};
type ChatJobRun={status:string;result?:{errorMessage?:string}|null};
const input={background:'#0d0d14',color:'#e2e8f0',border:'1px solid #252532',borderRadius:6,padding:'.55rem .7rem'};const button={background:'#4f46e5',color:'white',border:0,borderRadius:6,padding:'.55rem .9rem',cursor:'pointer'};const label={color:'#94a3b8',display:'flex',gap:6,alignItems:'center'};
const card={background:'#111118',border:'1px solid #252532',borderRadius:9,padding:'1rem',marginBottom:'1rem'};
function ActionOptions(){return <><option value="log">Log only</option><option value="warn">Warn player</option><option value="kick">Kick player</option></>;}
function withTimeout<T>(promise:Promise<T>,milliseconds:number,message:string):Promise<T>{return Promise.race([promise,new Promise<T>((_,reject)=>setTimeout(()=>reject(new Error(message)),milliseconds))]);}
